resolver: lts-22.21

packages:
  - .

ghc-options:
  "$locals": -Wall

allow-newer: false

extra-deps:
  - smtp-mail-0.5.0.1
  - mime-mail-0.5.1

flags:
  hashtables:
    portable: true
    sse42: false
    unsafe-tricks: false
  warp:
    x509: false
