{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE EmptyDataDecls #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE MultiParamTypeClasses #-}

module DAL.Schema
  ( Schema(..)
  , Entity(..)
  , Field(..)
  , FieldType(..)
  , EntityField(..)
  , migrateAll
  , EventStoreEntity(..)
  , EventSnapshotEntity(..)
  , AccountingEventEntity(..)
  , AuditLogEntity(..)
  , UserRoleEntity(..)
  , PermissionEntity(..)
  , RolePermissionEntity(..)
  ) where

import Data.Aeson (FromJSON, ToJSON)
import Data.Int (Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Time (UTCTime)
import Data.Yaml (Value)
import GHC.Generics (Generic)

-- Generated from dsl/schema.yaml
-- DO NOT EDIT MANUALLY

data Schema = Schema
  { schemaVersion :: !T.Text
  , schemaDomain  :: !T.Text
  , schemaDatabase :: !T.Text
  , schemaGenerator :: !T.Text
  , schemaGeneratorVersion :: !T.Text
  , schemaEntities :: ![Entity]
  } deriving (Show, Generic)

instance FromJSON Schema
instance ToJSON Schema

data Entity = Entity
  { entityName    :: !T.Text
  , entitySqlTable :: !T.Text
  , entityFields  :: ![Field]
  } deriving (Show, Generic)

instance FromJSON Entity
instance ToJSON Entity

data Field = Field
  { fieldName     :: !T.Text
  , fieldType     :: !FieldType
  , fieldSqlType  :: !T.Text
  , fieldDefault  :: !(Maybe T.Text)
  , fieldNullable :: !Bool
  } deriving (Show, Generic)

instance FromJSON Field
instance ToJSON Field

data FieldType
  = FTInteger
  | FTSerial
  | FTBigInt
  | FTBoolean
  | FTText
  | FTVarchar
  | FTChar
  | FTReal
  | FTDouble
  | FTNumeric
  | FTDate
  | FTTimestamp
  | FTTime
  | FTJsonb
  | FTLtree
  | FTRange
  | FTCidr
  | FTInet
  | FTMacAddr
  | FTGeometry
  deriving (Show, Generic)

instance FromJSON FieldType
instance ToJSON FieldType

-- DSL entities:
-- Entity: PersonEntity
-- SQL table: person
-- Field: code
-- Type: FTText
-- SQL type: text
-- Nullable: True
-- Default: 
-- Field: name
-- Type: FTText
-- SQL type: text
-- Nullable: False
-- Default: 
-- Field: inn
-- Type: FTText
-- SQL type: text
-- Nullable: True
-- Default: 
-- Field: kpp
-- Type: FTText
-- SQL type: text
-- Nullable: True
-- Default: 
-- Field: personType
-- Type: FTText
-- SQL type: integer
-- Nullable: False
-- Default: 
-- Field: status
-- Type: FTText
-- SQL type: integer
-- Nullable: True
-- Default: 
-- Entity: CustomerEntity
-- SQL table: customer
-- Field: code
-- Type: FTText
-- SQL type: text
-- Nullable: False
-- Default: 
-- Field: name
-- Type: FTText
-- SQL type: text
-- Nullable: False
-- Default: 
-- Field: email
-- Type: FTText
-- SQL type: text
-- Nullable: True
-- Default: 
-- Field: creditLimit
-- Type: FTText
-- SQL type: numeric
-- Nullable: True
-- Default: 
-- Field: active
-- Type: FTText
-- SQL type: boolean
-- Nullable: False
-- Default: 
-- Field: createdAt
-- Type: FTText
-- SQL type: date
-- Nullable: True
-- Default: 
-- Entity: ProductionOrderEntity
-- SQL table: production_order
-- Field: number
-- Type: FTText
-- SQL type: text
-- Nullable: False
-- Default: 
-- Field: productId
-- Type: FTText
-- SQL type: bigint
-- Nullable: False
-- Default: 
-- Field: qty
-- Type: FTText
-- SQL type: bigint
-- Nullable: False
-- Default: 
-- Field: dueDate
-- Type: FTText
-- SQL type: date
-- Nullable: True
-- Default: 
-- Field: status
-- Type: FTText
-- SQL type: integer
-- Nullable: False
-- Default: 
-- Entity: ReportConfigEntity
-- SQL table: report_config
-- Field: title
-- Type: FTText
-- SQL type: text
-- Nullable: False
-- Default: 
-- Field: query
-- Type: FTText
-- SQL type: text
-- Nullable: False
-- Default: 
-- Field: refreshMinutes
-- Type: FTText
-- SQL type: integer
-- Nullable: True
-- Default: 
-- Field: enabled
-- Type: FTText
-- SQL type: boolean
-- Nullable: False
-- Default: 

-- Generated by surypus-codegen

-- | Migrate all entities (Phase 1: no-op stub)
migrateAll :: IO ()
migrateAll = return ()

-- | Entity field selector (Phase 1: stub)
data EntityField
  = EventStoreEntityAggregateId
  | EventStoreEntityAggregateType
  | EventStoreEntityEventType
  | EventStoreEntityEventVersion
  | EventStoreEntityEventSchemaVersion
  | EventStoreEntityEventData
  | EventStoreEntityEventMetadata
  | EventStoreEntitySequenceNumber
  | EventStoreEntityOccurredAt
  | EventStoreEntityCreatedAt
  | RolePermissionEntityRoleId
  | RolePermissionEntityPermissionId
  | AuditLogEntityUserId
  | AuditLogEntityCreatedAt
  | EventSnapshotEntitySnapshotAggregateId
  | EventSnapshotEntitySnapshotAggregateType
  | EventSnapshotEntitySnapshotVersion
  | AccountingEventEntityEventId
  | AccountingEventEntityAggregateId
  | AccountingEventEntityAggregateType
  | AccountingEventEntityEventType
  | AccountingEventEntityEventVersion
  | AccountingEventEntityEventData
  | AccountingEventEntityMetadata
  | AccountingEventEntitySequenceNumber
  | AccountingEventEntityOccurredAt
  | AccountingEventEntityCreatedAt
  deriving (Show, Generic)

instance FromJSON EntityField
instance ToJSON EntityField

-- | Event store entity (Phase 1: stub)
data EventStoreEntity = EventStoreEntity
  { eventStoreEntityAggregateId       :: !Int64
  , eventStoreEntityAggregateType     :: !Text
  , eventStoreEntityEventType         :: !Text
  , eventStoreEntityEventVersion      :: !Int
  , eventStoreEntityEventSchemaVersion :: !Int
  , eventStoreEntityEventData         :: !Text
  , eventStoreEntityEventMetadata     :: !(Maybe Text)
  , eventStoreEntitySequenceNumber    :: !Int64
  , eventStoreEntityOccurredAt        :: !UTCTime
  , eventStoreEntityCreatedAt         :: !UTCTime
  } deriving (Show, Generic)

instance FromJSON EventStoreEntity
instance ToJSON EventStoreEntity

-- | Event snapshot entity (Phase 1: stub)
data EventSnapshotEntity = EventSnapshotEntity
  { eventSnapshotEntitySnapshotAggregateId   :: !Int64
  , eventSnapshotEntitySnapshotAggregateType :: !Text
  , eventSnapshotEntitySnapshotVersion       :: !Int
  , eventSnapshotEntitySnapshotLastSeq        :: !Int64
  , eventSnapshotEntitySnapshotData          :: !Text
  , eventSnapshotEntitySnapshotCreatedAt     :: !UTCTime
  } deriving (Show, Generic)

instance FromJSON EventSnapshotEntity
instance ToJSON EventSnapshotEntity

-- | Accounting event entity (Phase 1: stub)
data AccountingEventEntity = AccountingEventEntity
  { accountingEventEntityEventId       :: !Int64
  , accountingEventEntityAggregateId   :: !Int64
  , accountingEventEntityAggregateType :: !Text
  , accountingEventEntityEventType     :: !Text
  , accountingEventEntityEventVersion  :: !Int
  , accountingEventEntityEventData     :: !Text
  , accountingEventEntityMetadata      :: !(Maybe Text)
  , accountingEventEntitySequenceNumber :: !Int64
  , accountingEventEntityOccurredAt    :: !UTCTime
  , accountingEventEntityCreatedAt     :: !UTCTime
  } deriving (Show, Generic)

instance FromJSON AccountingEventEntity
instance ToJSON AccountingEventEntity

-- | Audit log entity (Phase 1: stub)
data AuditLogEntity = AuditLogEntity
  { auditLogEntityId      :: !Int64
  , auditLogEntityUserId  :: !Int64
  , auditLogEntityAction  :: !Text
  , auditLogEntityDetails :: !(Maybe Text)
  , auditLogEntityResourceType :: !(Maybe Text)
  , auditLogEntityResourceId :: !(Maybe Text)
  , auditLogEntityOldValues :: !(Maybe Text)
  , auditLogEntityNewValues :: !(Maybe Text)
  , auditLogEntityIpAddress :: !(Maybe Text)
  , auditLogEntityCreatedAt :: !UTCTime
  } deriving (Show, Generic)

instance FromJSON AuditLogEntity
instance ToJSON AuditLogEntity

-- | User role entity (Phase 1: stub)
data UserRoleEntity = UserRoleEntity
  { userRoleEntityId   :: !Int64
  , userRoleEntityUserId :: !Int64
  , userRoleEntityRoleId :: !Int64
  } deriving (Show, Generic)

instance FromJSON UserRoleEntity
instance ToJSON UserRoleEntity

-- | Permission entity (Phase 1: stub)
data PermissionEntity = PermissionEntity
  { permissionEntityId   :: !Int64
  , permissionEntityName :: !Text
  , permissionEntityCode :: !Text
  } deriving (Show, Generic)

instance FromJSON PermissionEntity
instance ToJSON PermissionEntity

-- | Role permission entity (Phase 1: stub)
data RolePermissionEntity = RolePermissionEntity
  { rolePermissionEntityId   :: !Int64
  , rolePermissionEntityRoleId :: !Int64
  , rolePermissionEntityPermissionId :: !Int64
  } deriving (Show, Generic)

instance FromJSON RolePermissionEntity
instance ToJSON RolePermissionEntity
