{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE EmptyDataDecls #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE MultiParamTypeClasses #-}

module DAL.Schema
  ( Schema(..)
  , Entity(..)
  , Field(..)
  , FieldType(..)
  , EntityField(..)
  , migrateAll
  , EventStoreEntity(..)
  , EventSnapshotEntity(..)
  , AccountingEventEntity(..)
  , AuditLogEntity(..)
  , UserRoleEntity(..)
  , PermissionEntity(..)
  , RolePermissionEntity(..)
  ) where

import Data.Aeson (FromJSON, ToJSON)
import Data.Int (Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Time (UTCTime)
import Data.Yaml (Value)
import GHC.Generics (Generic)

-- Generated from dsl/schema.yaml
-- DO NOT EDIT MANUALLY

data Schema = Schema
  { schemaVersion :: !T.Text
  , schemaDomain  :: !T.Text
  , schemaDatabase :: !T.Text
  , schemaGenerator :: !T.Text
  , schemaGeneratorVersion :: !T.Text
  , schemaEntities :: ![Entity]
  } deriving (Show, Generic)

instance FromJSON Schema
instance ToJSON Schema

data Entity = Entity
  { entityName    :: !T.Text
  , entitySqlTable :: !T.Text
  , entityFields  :: ![Field]
  } deriving (Show, Generic)

instance FromJSON Entity
instance ToJSON Entity

data Field = Field
  { fieldName     :: !T.Text
  , fieldType     :: !FieldType
  , fieldSqlType  :: !T.Text
  , fieldDefault  :: !(Maybe T.Text)
  , fieldNullable :: !Bool
  } deriving (Show, Generic)

instance FromJSON Field
instance ToJSON Field

data FieldType
  = FTInteger
  | FTSerial
  | FTBigInt
  | FTBoolean
  | FTText
  | FTVarchar
  | FTChar
  | FTReal
  | FTDouble
  | FTNumeric
  | FTDate
  | FTTimestamp
  | FTTime
  | FTJsonb
  | FTLtree
  | FTRange
  | FTCidr
  | FTInet
  | FTMacAddr
  | FTGeometry
  deriving (Show, Generic)

instance FromJSON FieldType
instance ToJSON FieldType

-- DSL entities:
-- Entity: PersonEntity
-- SQL table: person
-- Field: code
-- Type: FTText
-- SQL type: text
-- Nullable: True
-- Default: 
-- Field: name
-- Type: FTText
-- SQL type: text
-- Nullable: False
-- Default: 
-- Field: inn
-- Type: FTText
-- SQL type: text
-- Nullable: True
-- Default: 
-- Field: kpp
-- Type: FTText
-- SQL type: text
-- Nullable: True
-- Default: 
-- Field: personType
-- Type: FTText
-- SQL type: integer
-- Nullable: False
-- Default: 
-- Field: status
-- Type: FTText
-- SQL type: integer
-- Nullable: True
-- Default: 
-- Entity: CustomerEntity
-- SQL table: customer
-- Field: code
-- Type: FTText
-- SQL type: text
-- Nullable: False
-- Default: 
-- Field: name
-- Type: FTText
-- SQL type: text
-- Nullable: False
-- Default: 
-- Field: email
-- Type: FTText
-- SQL type: text
-- Nullable: True
-- Default: 
-- Field: creditLimit
-- Type: FTText
-- SQL type: numeric
-- Nullable: True
-- Default: 
-- Field: active
-- Type: FTText
-- SQL type: boolean
-- Nullable: False
-- Default: 
-- Field: createdAt
-- Type: FTText
-- SQL type: date
-- Nullable: True
-- Default: 
-- Entity: ProductionOrderEntity
-- SQL table: production_order
-- Field: number
-- Type: FTText
-- SQL type: text
-- Nullable: False
-- Default: 
-- Field: productId
-- Type: FTText
-- SQL type: bigint
-- Nullable: False
-- Default: 
-- Field: qty
-- Type: FTText
-- SQL type: bigint
-- Nullable: False
-- Default: 
-- Field: dueDate
-- Type: FTText
-- SQL type: date
-- Nullable: True
-- Default: 
-- Field: status
-- Type: FTText
-- SQL type: integer
-- Nullable: False
-- Default: 
-- Entity: ReportConfigEntity
-- SQL table: report_config
-- Field: title
-- Type: FTText
-- SQL type: text
-- Nullable: False
-- Default: 
-- Field: query
-- Type: FTText
-- SQL type: text
-- Nullable: False
-- Default: 
-- Field: refreshMinutes
-- Type: FTText
-- SQL type: integer
-- Nullable: True
-- Default: 
-- Field: enabled
-- Type: FTText
-- SQL type: boolean
-- Nullable: False
-- Default: 

-- Generated by surypus-codegen

-- | Migrate all entities (Phase 1: no-op stub)
migrateAll :: IO ()
migrateAll = return ()

-- | Entity field selector (Phase 1: stub)
data EntityField
  = EventStoreEntityAggregateId
  | EventStoreEntityAggregateType
  | EventStoreEntityEventType
  | EventStoreEntityEventVersion
  | EventStoreEntityEventSchemaVersion
  | EventStoreEntityEventData
  | EventStoreEntityEventMetadata
  | EventStoreEntitySequenceNumber
  | EventStoreEntityOccurredAt
  | EventStoreEntityCreatedAt
  | UserRoleEntityUserId
  | UserRoleEntityRoleId
  | PermissionEntityName
  | PermissionEntityDescription
  | RolePermissionEntityRoleId
  | RolePermissionEntityPermissionId
  | AuditLogEntityUserId
  | AuditLogEntityCreatedAt
  | EventSnapshotEntitySnapshotAggregateId
  | EventSnapshotEntitySnapshotAggregateType
  | EventSnapshotEntitySnapshotVersion
  | AccountingEventEntityEventId
  | AccountingEventEntityAggregateId
  | AccountingEventEntityAggregateType
  | AccountingEventEntityEventType
  | AccountingEventEntityEventVersion
  | AccountingEventEntityEventData
  | AccountingEventEntityMetadata
  | AccountingEventEntitySequenceNumber
  | AccountingEventEntityOccurredAt
  | AccountingEventEntityCreatedAt
  deriving (Show, Generic)

instance FromJSON EntityField
instance ToJSON EntityField

-- | Event store entity (Phase 1: stub)
data EventStoreEntity = EventStoreEntity
  { eventStoreEntityAggregateId       :: !Int64
  , eventStoreEntityAggregateType     :: !Text
  , eventStoreEntityEventType         :: !Text
  , eventStoreEntityEventVersion      :: !Int
  , eventStoreEntityEventSchemaVersion :: !Int
  , eventStoreEntityEventData         :: !Text
  , eventStoreEntityEventMetadata     :: !(Maybe Text)
  , eventStoreEntitySequenceNumber    :: !Int64
  , eventStoreEntityOccurredAt        :: !UTCTime
  , eventStoreEntityCreatedAt         :: !UTCTime
  } deriving (Show, Generic)

instance FromJSON EventStoreEntity
instance ToJSON EventStoreEntity

-- | Event snapshot entity (Phase 1: stub)
data EventSnapshotEntity = EventSnapshotEntity
  { eventSnapshotEntitySnapshotAggregateId   :: !Int64
  , eventSnapshotEntitySnapshotAggregateType :: !Text
  , eventSnapshotEntitySnapshotVersion       :: !Int
  , eventSnapshotEntitySnapshotLastSeq        :: !Int64
  , eventSnapshotEntitySnapshotData          :: !Text
  , eventSnapshotEntitySnapshotCreatedAt     :: !UTCTime
  } deriving (Show, Generic)

instance FromJSON EventSnapshotEntity
instance ToJSON EventSnapshotEntity

-- | Accounting event entity (Phase 1: stub)
data AccountingEventEntity = AccountingEventEntity
  { accountingEventEntityEventId       :: !Int64
  , accountingEventEntityAggregateId   :: !Int64
  , accountingEventEntityAggregateType :: !Text
  , accountingEventEntityEventType     :: !Text
  , accountingEventEntityEventVersion  :: !Int
  , accountingEventEntityEventData     :: !Text
  , accountingEventEntityMetadata      :: !(Maybe Text)
  , accountingEventEntitySequenceNumber :: !Int64
  , accountingEventEntityOccurredAt    :: !UTCTime
  , accountingEventEntityCreatedAt     :: !UTCTime
  } deriving (Show, Generic)

instance FromJSON AccountingEventEntity
instance ToJSON AccountingEventEntity

-- | Audit log entity (Phase 1: stub)
data AuditLogEntity = AuditLogEntity
  { auditLogEntityId      :: !Int64
  , auditLogEntityUserId  :: !Int64
  , auditLogEntityAction  :: !Text
  , auditLogEntityDetails :: !(Maybe Text)
  , auditLogEntityResourceType :: !(Maybe Text)
  , auditLogEntityResourceId :: !(Maybe Text)
  , auditLogEntityOldValues :: !(Maybe Text)
  , auditLogEntityNewValues :: !(Maybe Text)
  , auditLogEntityIpAddress :: !(Maybe Text)
  , auditLogEntityCreatedAt :: !UTCTime
  } deriving (Show, Generic)

instance FromJSON AuditLogEntity
instance ToJSON AuditLogEntity

-- | User role entity (Phase 1: stub)
data UserRoleEntity = UserRoleEntity
  { userRoleEntityId   :: !Int64
  , userRoleEntityUserId :: !Int64
  , userRoleEntityRoleId :: !Int64
  } deriving (Show, Generic)

instance FromJSON UserRoleEntity
instance ToJSON UserRoleEntity

-- | Permission entity (Phase 1: stub)
data PermissionEntity = PermissionEntity
  { permissionEntityId   :: !Int64
  , permissionEntityName :: !Text
  , permissionEntityCode :: !Text
  } deriving (Show, Generic)

instance FromJSON PermissionEntity
instance ToJSON PermissionEntity

-- | Role permission entity (Phase 1: stub)
data RolePermissionEntity = RolePermissionEntity
  { rolePermissionEntityId   :: !Int64
  , rolePermissionEntityRoleId :: !Int64
  , rolePermissionEntityPermissionId :: !Int64
  } deriving (Show, Generic)

instance FromJSON RolePermissionEntity
instance ToJSON RolePermissionEntity

-- | Person entity (Phase 1: stub)
data PersonEntity = PersonEntity
  { personEntityId :: !Int64
  , personEntityCode :: !Text
  , personEntityName :: !Text
  , personEntityInn :: !(Maybe Text)
  , personEntityKpp :: !(Maybe Text)
  , personEntityPersonType :: !(Maybe Text)
  , personEntityStatus :: !(Maybe Text)
  } deriving (Show, Generic)

instance FromJSON PersonEntity
instance ToJSON PersonEntity

-- | Goods entity (Phase 1: stub)
data GoodsEntity = GoodsEntity
  { goodsEntityId :: !Int64
  , goodsEntityCode :: !Text
  , goodsEntityName :: !Text
  , goodsEntityFullName :: !(Maybe Text)
  , goodsEntityBarcode :: !(Maybe Text)
  , goodsEntityUnitId :: !(Maybe Int64)
  , goodsEntityCategoryId :: !(Maybe Int64)
  , goodsEntityGoodsType :: !(Maybe Text)
  , goodsEntityGoodsStatus :: !(Maybe Text)
  , goodsEntityMinStock :: !(Maybe Double)
  , goodsEntityMaxStock :: !(Maybe Double)
  , goodsEntityWeight :: !(Maybe Double)
  , goodsEntityVolume :: !(Maybe Double)
  } deriving (Show, Generic)

instance FromJSON GoodsEntity
instance ToJSON GoodsEntity

-- | Bill entity (Phase 1: stub)
data BillEntity = BillEntity
  { billEntityId :: !Int64
  , billEntityBillNumber :: !(Maybe Text)
  , billEntityBillDate :: !(Maybe UTCTime)
  , billEntityCustomerId :: !(Maybe Int64)
  , billEntityVendorId :: !(Maybe Int64)
  , billEntityWarehouseId :: !(Maybe Int64)
  , billEntityCurrencyId :: !(Maybe Int64)
  , billEntityBillStatus :: !(Maybe Text)
  , billEntityBillType :: !(Maybe Text)
  , billEntitySubtotal :: !(Maybe Double)
  , billEntityTaxAmount :: !(Maybe Double)
  , billEntityTotalAmount :: !(Maybe Double)
  , billEntityPaidAmount :: !(Maybe Double)
  , billEntityNotes :: !(Maybe Text)
  , billEntityCreatedAt :: !(Maybe UTCTime)
  , billEntityUpdatedAt :: !(Maybe UTCTime)
  } deriving (Show, Generic)

instance FromJSON BillEntity
instance ToJSON BillEntity

-- | Bill line entity (Phase 1: stub)
data BillLineEntity = BillLineEntity
  { billLineEntityId :: !Int64
  , billLineEntityBillId :: !Int64
  , billLineEntityGoodsId :: !Int64
  , billLineEntityQtty :: !Double
  , billLineEntityPrice :: !Double
  , billLineEntityDiscountAmount :: !Double
  , billLineEntityAmount :: !Double
  } deriving (Show, Generic)

instance FromJSON BillLineEntity
instance ToJSON BillLineEntity

-- | Location entity (Phase 1: stub)
data LocationEntity = LocationEntity
  { locationEntityId :: !Int64
  , locationEntityCode :: !Text
  , locationEntityName :: !Text
  } deriving (Show, Generic)

instance FromJSON LocationEntity
instance ToJSON LocationEntity

-- | Lot entity (Phase 1: stub)
data LotEntity = LotEntity
  { lotEntityId :: !Int64
  , lotEntityCode :: !Text
  , lotEntityGoodsId :: !Int64
  , lotEntityQuantity :: !Double
  } deriving (Show, Generic)

instance FromJSON LotEntity
instance ToJSON LotEntity

-- | Tenant entity (Phase 1: stub)
data TenantEntity = TenantEntity
  { tenantEntityId :: !Int64
  , tenantEntityName :: !Text
  } deriving (Show, Generic)

instance FromJSON TenantEntity
instance ToJSON TenantEntity

-- | Tax entity (Phase 1: stub)
data TaxEntity = TaxEntity
  { taxEntityId :: !Int64
  , taxEntityCode :: !Text
  , taxEntityName :: !Text
  , taxEntityRate :: !Double
  } deriving (Show, Generic)

instance FromJSON TaxEntity
instance ToJSON TaxEntity

-- | Currency entity (Phase 1: stub)
data CurrencyEntity = CurrencyEntity
  { currencyEntityId :: !Int64
  , currencyEntityCode :: !Text
  , currencyEntityName :: !Text
  } deriving (Show, Generic)

instance FromJSON CurrencyEntity
instance ToJSON CurrencyEntity

-- | Employee entity (Phase 1: stub)
data EmployeeEntity = EmployeeEntity
  { employeeEntityId :: !Int64
  , employeeEntityCode :: !Text
  , employeeEntityFirstName :: !Text
  , employeeEntityLastName :: !(Maybe Text)
  } deriving (Show, Generic)

instance FromJSON EmployeeEntity
instance ToJSON EmployeeEntity

-- | Document type entity (Phase 1: stub)
data DocumentTypeEntity = DocumentTypeEntity
  { documentTypeEntityId :: !Int64
  , documentTypeEntityCode :: !Text
  , documentTypeEntityName :: !Text
  , documentTypeEntityDescription :: !(Maybe Text)
  } deriving (Show, Generic)

instance FromJSON DocumentTypeEntity
instance ToJSON DocumentTypeEntity

-- | Order head entity (Phase 1: stub)
data OrderHeadEntity = OrderHeadEntity
  { orderHeadEntityId :: !Int64
  , orderHeadEntityCode :: !Text
  , orderHeadEntityName :: !Text
  , orderHeadEntityDocDate :: !UTCTime
  , orderHeadEntityPersonId :: !(Maybe Int64)
  , orderHeadEntityLocationId :: !(Maybe Int64)
  , orderHeadEntityDocType :: !(Maybe Text)
  , orderHeadEntityTotal :: !(Maybe Double)
  , orderHeadEntityDiscountAmount :: !(Maybe Double)
  , orderHeadEntityTaxAmount :: !(Maybe Double)
  } deriving (Show, Generic)

instance FromJSON OrderHeadEntity
instance ToJSON OrderHeadEntity

-- | Goods price entity (Phase 1: stub)
data GoodsPriceEntity = GoodsPriceEntity
  { goodsPriceEntityId :: !Int64
  , goodsPriceEntityGoodsId :: !Int64
  , goodsPriceEntityPriceType :: !(Maybe Text)
  , goodsPriceEntityPrice :: !Double
  , goodsPriceEntityMinPrice :: !(Maybe Double)
  , goodsPriceEntityStartDate :: !(Maybe UTCTime)
  , goodsPriceEntityEndDate :: !(Maybe UTCTime)
  } deriving (Show, Generic)

instance FromJSON GoodsPriceEntity
instance ToJSON GoodsPriceEntity
