{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE EmptyDataDecls #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE MultiParamTypeClasses #-}

module DAL.Types where

import Data.Aeson (FromJSON, ToJSON)
import qualified Data.Text as T
import GHC.Generics (Generic)

-- Generated from dsl/schema.yaml
-- DO NOT EDIT MANUALLY

-- DSL entities:
-- Entity: PersonEntity
-- SQL table: person
data PersonEntity = PersonEntity
  { personEntityId :: !T.Text
  , code :: !T.Text
  , name :: !T.Text
  , inn :: !T.Text
  , kpp :: !T.Text
  , personType :: !T.Text
  , status :: !T.Text
  } deriving (Show, Generic)

instance FromJSON (PersonEntity)
instance ToJSON (PersonEntity)

-- Entity: CustomerEntity
-- SQL table: customer
data CustomerEntity = CustomerEntity
  { customerEntityId :: !T.Text
  , code :: !T.Text
  , name :: !T.Text
  , email :: !T.Text
  , creditLimit :: !T.Text
  , active :: !T.Text
  , createdAt :: !T.Text
  } deriving (Show, Generic)

instance FromJSON (CustomerEntity)
instance ToJSON (CustomerEntity)

-- Entity: ProductionOrderEntity
-- SQL table: production_order
data ProductionOrderEntity = ProductionOrderEntity
  { productionOrderEntityId :: !T.Text
  , number :: !T.Text
  , productId :: !T.Text
  , qty :: !T.Text
  , dueDate :: !T.Text
  , status :: !T.Text
  } deriving (Show, Generic)

instance FromJSON (ProductionOrderEntity)
instance ToJSON (ProductionOrderEntity)

-- Entity: ReportConfigEntity
-- SQL table: report_config
data ReportConfigEntity = ReportConfigEntity
  { reportConfigEntityId :: !T.Text
  , title :: !T.Text
  , query :: !T.Text
  , refreshMinutes :: !T.Text
  , enabled :: !T.Text
  } deriving (Show, Generic)

instance FromJSON (ReportConfigEntity)
instance ToJSON (ReportConfigEntity)

-- Entity: BillEntity
-- SQL table: bill
data BillEntity = BillEntity
  { billEntityId :: !T.Text
  , billEntityNumber :: !T.Text
  , billEntityCustomerId :: !T.Text
  , billEntityTotal :: !T.Text
  , billEntityStatus :: !T.Text
  } deriving (Show, Generic)

instance FromJSON (BillEntity)
instance ToJSON (BillEntity)

-- Entity: TaxEntity
-- SQL table: tax
data TaxEntity = TaxEntity
  { taxEntityId :: !T.Text
  , taxEntityCode :: !T.Text
  , taxEntityName :: !T.Text
  , taxEntityRate :: !T.Text
  } deriving (Show, Generic)

instance FromJSON (TaxEntity)
instance ToJSON (TaxEntity)

-- | Pagination parameters (Phase 1: stub)
data Pagination = Pagination
  { paginationOffset :: !Int
  , paginationLimit  :: !Int
  } deriving (Show, Generic)

instance FromJSON Pagination
instance ToJSON Pagination

-- | Query result wrapper (Phase 1: stub)
data QueryResult a = QueryResult
  { queryResultData  :: ![a]
  , queryResultTotal :: !Int
  } deriving (Show, Generic)

instance FromJSON a => FromJSON (QueryResult a)
instance ToJSON a => ToJSON (QueryResult a)

-- Generated by surypus-codegen
